### ISSUE TITLE
Request key packages based on user ID? (or send many DSRequests)

### ISSUE THREAD

**Issue by turt2live** [ietf-wg-mimi/mimi-protocol#28]
> **TODO**: For now, the event fetches key packages based on client identifiers,
> not user identifiers. This is because KeyPackage fetching is part of MIMI DS,
> which doesn't know what a user is. We could, however, send multiple MIMI DS
> requests in a single MIMI protocol request.

**Comment by rohanmahy** [comment]
This is actually no longer the case. the current document fetches based on user. Closing.
