### ISSUE TITLE
Clarify fanout throughout

### ISSUE THREAD

**Issue by turt2live** [ietf-wg-mimi/mimi-protocol#30]
Which events are sent to who, and how? Specifically DS Welcome events.

**Comment by turt2live** [comment]
> **TODO**: Especially when adding new clients, we will want to forward a
> `ds.commit` event selectively, as existing group members will only be
> interested in the actual commit, whereas new group members only need the
> Welcome.

**Comment by rohanmahy** [comment]
I think this is now pretty clear. I propose we close this one.
