### ISSUE TITLE
Security properties of GroupInfo

### ISSUE THREAD

**Issue by turt2live** [ietf-wg-mimi/mimi-protocol#31]
> **TODO**: in the MLS case, what security properties are needed to protect a
> GroupInfo object in the MIMI context are still under discussion. It is
> possible that the requester only needs to prove possession of their private
> key. The GroupInfo in another context might be sufficiently sensitive that it
> should be encrypted from the end client to the hub provider (unreadable by the
> local provider).

**Comment by kkohbrok** [comment]
The same security should probably apply to an `m.room.info` event proposed in #23.

**Comment by rohanmahy** [comment]
GroupInfo is now protected from the external joiner's provider during fetch in #86 . It can be protected from the committer's provider in #85 . Closing.
