### ISSUE TITLE
Fix `ds.send_message`

### ISSUE THREAD

**Issue by turt2live** [ietf-wg-mimi/mimi-protocol#34]
> **TODO**: This is not a proposal and there is no way for the Hub or follower servers
> to authenticate this event at the moment. We might want to a way to do that
> later.

(thoughts welcome)

**Comment by kkohbrok** [comment]
Some context: Application messages are signed, but the sender data is encrypted to protect the associated metadata. Only clients can decrypt the sender data and thus authenticate the message.

**Comment by rohanmahy** [comment]
I believe the current submitMessage primitive has appropriate authorization now. Closing.
