### ISSUE TITLE
Do we need `m.room.info`?

### ISSUE THREAD

**Issue by turt2live** [ietf-wg-mimi/mimi-protocol#35]
see title

**Comment by kkohbrok** [comment]
For context: If the room state is included fully (and not just as a hash) in the group state, it can be retrieved it via `ds.fetch_group_info`. `m.room.info` is thus somewhat redundant.

**Comment by rohanmahy** [comment]
I think the original intent of this was that clients would get informed of changes to the room and room policy, which I think is covered under the current architecture. Closing. (Please reopen a more specific issue if I missed something).
