### ISSUE TITLE
Prepare document for IETF 118

### ISSUE THREAD

**Issue by kkohbrok** [ietf-wg-mimi/mimi-protocol#6]
Tasks:

- [x] #7
- [x] #9
- [ ] Merge m.room.create event and m.room.participant_list into single event?
- [ ] #11
- [ ] Define struct to use for fan-out messages, or better even a general MIMI message struct, which can contain an event or a fan-out message
- [ ] Update #3 by replacing the individual structs with links to various parts of the document
- [ ] Go over introduction and abstract

Maybe move to after IETF 118
- [ ] Change event naming scheme away from `m.xxx.yyy`?
- [ ] Add section on Adds (representing a "forced join")
- [ ] Allow patch-style operation instead of the current one-change-at-a time mechanism in m.room.user event
- [ ] Figure out if KeyPackage retrieval should be tied to a room (at least optionally)

**Comment by tgeoghegan** [comment]
IETF 118 is long over, everything here is stale per Richard.
